language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -m nltk.downloader stopwords
  - python -m nltk.downloader averaged_perceptron_tagger
# command to run tests
script:
  - pytest
